# Generated by Django 5.0.1 on 2024-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="daytask",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="monthlytask",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
