# Generated by Django 5.0.1 on 2024-01-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0003_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlytask",
            name="day_of_month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("0", "Monday"),
                    ("1", "Tuesday"),
                    ("2", "Wednesday"),
                    ("3", "Thursday"),
                    ("4", "Friday"),
                    ("5", "Saturday"),
                    ("6", "Sunday"),
                ],
                default="0",
                max_length=9,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
